<a href="https://colab.research.google.com/github/fcojquesada/Linear-Regression-Pyhton-Colab/blob/main/sklearn%2B_%2BMultiple%2BLinear%2BRegression%2Band%2BAdjusted%2BR_squared%2B_%2BExercise%2BSolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adjusted R-squared - Exercise Solution

Using the code from the lecture, create a function which will calculate the adjusted R-squared for you, given the independent variable(s) (x) and the dependent variable (y).

Check if you function is working properly.

Solution at the bottom.

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Regression itself

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### Calculating the R-squared

In [8]:
reg.score(x,y)

0.4066811952814283

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [9]:
x.shape

(84, 2)

In [10]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Adjusted R^2 function

In [11]:
# There are different ways to solve this problem
# To make it as easy and interpretable as possible, we have preserved the original code
def adj_r2(x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [12]:
# Here's the result
adj_r2(x,y)

0.3920313482513401

# Feature Selection
### Determine which variables we can disregard, (the ones their p-values are higher than 0.05)

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [21]:
p_values.round(3)

array([0.   , 0.676])

In [38]:
reg_summary = pd.DataFrame(x.columns.values,columns=['Features'])
reg_summary['Coeficients'] = reg.coef_.round(5)
reg_summary['p-values'] = p_values.round(3)

In [39]:
reg_summary

Features  Coeficients  p-values
0         SAT      0.00165     0.000
1  Rand 1,2,3     -0.00827     0.676

### Standardization

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler = StandardScaler()

In [42]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [43]:
x_scaled = scaler.transform(x)

In [67]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

##New Regression with scaled input

In [45]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [47]:
reg.intercept_

3.330238095238095

##Summary table

In [57]:
reg_summary_scaled = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])

In [58]:
reg_summary_scaled['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]

In [60]:
reg_summary_scaled

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

We don't really care if a useless variable is there or not.

This is also one of the main reasons why S.K. learned does not natively support p values since most

M.L. practitioners perform some kind of feature scaling before fitting a model.

We don't really need to identify the worst performing features they are automatically penalized by having

a very small weight.

#Making Predictions with scaled values

In [61]:
new_data = pd.DataFrame([[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [62]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

This result doesn't look like they are correct values for a GPA
That's because we need to transform the values of the new_data

In [63]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [64]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

### What if we removed the variable Rand 1,2,3

In [80]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [81]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

So we see the predictions haven't being affected by the variables irrelevant